<?php

namespace Proxies\__CG__\Squad\FttBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Club extends \Squad\FttBundle\Entity\Club implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'idClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'libelleClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'emplacementClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'nbreTerrains', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'descriptionClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'imgClub', 'oldFile', 'tempFile', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'file'];
        }

        return ['__isInitialized__', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'idClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'libelleClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'emplacementClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'nbreTerrains', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'descriptionClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'imgClub', 'oldFile', 'tempFile', '' . "\0" . 'Squad\\FttBundle\\Entity\\Club' . "\0" . 'file'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Club $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdClub()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdClub();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClub', []);

        return parent::getIdClub();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleClub', []);

        return parent::getLibelleClub();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmplacementClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmplacementClub', []);

        return parent::getEmplacementClub();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreTerrains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreTerrains', []);

        return parent::getNbreTerrains();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionClub', []);

        return parent::getDescriptionClub();
    }

    /**
     * {@inheritDoc}
     */
    public function getImgClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgClub', []);

        return parent::getImgClub();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdClub($idClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdClub', [$idClub]);

        return parent::setIdClub($idClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleClub($libelleClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleClub', [$libelleClub]);

        return parent::setLibelleClub($libelleClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmplacementClub($emplacementClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmplacementClub', [$emplacementClub]);

        return parent::setEmplacementClub($emplacementClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreTerrains($nbreTerrains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreTerrains', [$nbreTerrains]);

        return parent::setNbreTerrains($nbreTerrains);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionClub($descriptionClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionClub', [$descriptionClub]);

        return parent::setDescriptionClub($descriptionClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setImgClub($imgClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgClub', [$imgClub]);

        return parent::setImgClub($imgClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

}
