security:
    encoders:
        FTT\UserBundle\Entity\Utilisateur: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_RESPONSABLE, ROLE_ARBITRE, ROLE_ADMIN,ROLE_FAN,ROLE_MEDECIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        main:
            id: fos_user.user_provider.username
           
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                success_handler: redirect.after.login                
            logout:
                path:   logout
                target: /login
            remember_me:
                key:   %secret% 
    access_control:

        - { path: ^/admin/, roles: ROLE_ADMIN}
        - { path: ^/arbitre/, roles: ROLE_ARBITRE}
        - { path: ^/medecin/, roles: ROLE_MEDECIN}