<?php

namespace Proxies\__CG__\Squad\FttBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Joueur extends \Squad\FttBundle\Entity\Joueur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'cinJoueur', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'nom', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'prenom', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'dateDeNaissance', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'categorie', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'pointAquis', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'taille', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'poids', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'mainForte', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'nationaliterJoueur', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'path', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'clubClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'file'];
        }

        return ['__isInitialized__', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'cinJoueur', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'nom', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'prenom', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'dateDeNaissance', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'categorie', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'pointAquis', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'taille', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'poids', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'mainForte', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'nationaliterJoueur', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'path', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'clubClub', '' . "\0" . 'Squad\\FttBundle\\Entity\\Joueur' . "\0" . 'file'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Joueur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCinJoueur()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCinJoueur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinJoueur', []);

        return parent::getCinJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function getPointAquis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointAquis', []);

        return parent::getPointAquis();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function getPoids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoids', []);

        return parent::getPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function getMainForte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainForte', []);

        return parent::getMainForte();
    }

    /**
     * {@inheritDoc}
     */
    public function getNationaliterJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationaliterJoueur', []);

        return parent::getNationaliterJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getClubClub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubClub', []);

        return parent::getClubClub();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinJoueur($cinJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinJoueur', [$cinJoueur]);

        return parent::setCinJoueur($cinJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance(\DateTime $dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$dateDeNaissance]);

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setPointAquis($pointAquis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointAquis', [$pointAquis]);

        return parent::setPointAquis($pointAquis);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille($taille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function setPoids($poids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoids', [$poids]);

        return parent::setPoids($poids);
    }

    /**
     * {@inheritDoc}
     */
    public function setMainForte($mainForte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainForte', [$mainForte]);

        return parent::setMainForte($mainForte);
    }

    /**
     * {@inheritDoc}
     */
    public function setNationaliterJoueur($nationaliterJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationaliterJoueur', [$nationaliterJoueur]);

        return parent::setNationaliterJoueur($nationaliterJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function setClubClub($clubClub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClubClub', [$clubClub]);

        return parent::setClubClub($clubClub);
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
