sanction:
    path:     /
    defaults: { _controller: "SquadFttBundle:Sanction:index" }

sanction_show:
    path:     /{id}/show
    defaults: { _controller: "SquadFttBundle:Sanction:show" }

sanction_new:
    path:     /new
    defaults: { _controller: "SquadFttBundle:Sanction:new" }

sanction_create:
    path:     /create
    defaults: { _controller: "SquadFttBundle:Sanction:create" }
    methods:  POST

sanction_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquadFttBundle:Sanction:edit" }

sanction_update:
    path:     /{id}/update
    defaults: { _controller: "SquadFttBundle:Sanction:update" }
    methods:  [POST, PUT]

sanction_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquadFttBundle:Sanction:delete" }
    methods:  [POST, DELETE]
sanction_joueur:
    path:     /joueur
    defaults: { _controller: "SquadFttBundle:Sanction:listJoueur" }
